### ISSUE TITLE
onlyoffice3.socket failed

### ISSUE THREAD

**Issue by leozero** [ONLYOFFICE/Docker-CommunityServer#6]
I have this error with nginx, so few static files are'nt loaded (css, js, ...) so it's not possible to use onlyoffice.

2016/02/24 17:26:53 [error] 710#0: *150 connect() to unix:/var/run/onlyoffice/onlyoffice3.socket failed (111: Connection refused) while connecting to upstream, client: 81.56.75.62, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice3.socket:", host: "domain.com:8080"

2016/02/24 17:27:06 [error] 710#0: *152 connect() to unix:/var/run/onlyoffice/onlyoffice3.socket failed (111: Connection refused) while connecting to upstream, client: 81.56.75.62, server: , request: "GET /discbundle/common/css/rZI8GL7qC28F1Yh_W2NrZg2.css?ver=264 HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice3.socket:", host: "erp.atosium.com:8080", referrer: "http://domain.com:8080/"

I checked in /var/run/onlyoffice and I have'nt onlyoffice3.socket

**Comment by l00v3** [comment]
For now, so you ca run it, you can "fix" it with this command, run it inside container:
ln -s /var/run/onlyoffice/onlyoffice2.socket /var/run/onlyoffice/onlyoffice3.socket
How to get inside container? You probably know this, if you got the logs, but maybe for somebody else
Run:
#docker ps
then copy the id and run
#docker attach $id
then run the link command
to get out of container, CTRL p and q

Simply linking socket3 to socket2 works, but it's dirty fix. Then restart the container and it should fix this problem. 

Check this thread on their dev forum and if you can, please check if you have any other problems and maybe write on the forum so we can open a discussion and maybe fix this quickly.
http://dev.onlyoffice.org/viewtopic.php?f=5&t=6801

Enjoy

**Comment by leokury** [comment]
I did the ln command but 404 errors still there. 

GET http://localhost/discbundle/common/javascript/FzoIB9G4wyYJlDezn5C0WA2.js?ver=264 
GET http://localhost/discbundle/common/css/h5Lk1cWqD9G0AAkON7R_4w2.css?ver=264 
GET http://localhost/discbundle/common/css/pyqwOjYUIzlMKq3OgsIyBg2.css?ver=264 
GET http://localhost/discbundle/common/css/jmE2c752T6GWBh2f6aU0lw2.css?ver=264 
GET http://localhost/discbundle/common/javascript/bdxfgU91U_fphmcJXdsizg2.js?ver=264 
GET http://localhost/discbundle/common/javascript/uhm8bzE5Ef1qYci0La-rXw2.js?ver=264 
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: AjaxPro is not defined

**Comment by leokury** [comment]
Added -h 127.0.0.1 to documentserver and community server and error are gone.

sudo docker run -i -t -d -h 127.0.0.1 --name onlyoffice-document-server onlyoffice/documentserver
sudo docker run -i -t -d -p 80:80 -p 5222:5222 -p 443:443 -h 127.0.0.1 \
> --link onlyoffice-document-server:document_server \
> onlyoffice/communityserver

**Comment by C-Duv** [comment]
On docker v1.11.0 (build 4dc5990), I get similar errors in the `logs/nginx.error.log` file:

```
2016/04/13 23:59:41 [crit] 720#0: *15 connect() to unix:/var/run/onlyoffice/onlyoffice3.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice3.socket:", host: "localhost"
2016/04/14 00:00:46 [crit] 720#0: *100 connect() to unix:/var/run/onlyoffice/onlyoffice3.socket failed (2: No such file or directory) while connecting to upstream, client: 172.17.42.1, server: , request: "GET /discbundle/common/css/YX9kvdMWJHm1M5Bxmvo6CA2.css?ver=264 HTTP/1.0", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice3.socket:", host: "docs.example.com", referrer: "https://docs.example.com/Startup.aspx"
2016/04/14 00:00:46 [error] 720#0: *100 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (11: Resource temporarily unavailable) while connecting to upstream, client: 172.17.42.1, server: , request: "GET /discbundle/common/css/YX9kvdMWJHm1M5Bxmvo6CA2.css?ver=264 HTTP/1.0", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "docs.example.com", referrer: "https://docs.example.com/Startup.aspx"
2016/04/14 00:01:02 [error] 720#0: *77 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.17.42.1, server: , request: "GET /skins/default/images/onlyoffice_logo/favicon_general.ico?t=635961887859375160 HTTP/1.0", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "docs.example.com", referrer: "https://docs.example.com/Startup.aspx"
2016/04/14 00:01:02 [error] 720#0: *7 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /warmup1/addons/calendar/default.aspx?warmup=true HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "localhost"
2016/04/14 00:01:02 [error] 720#0: *97 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.17.42.1, server: , request: "GET /discbundle/common/css/h5Lk1cWqD9G0AAkON7R_4w2.css?ver=264 HTTP/1.0", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "docs.example.com", referrer: "https://docs.example.com/Startup.aspx"
2016/04/14 00:01:02 [error] 720#0: *13 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /Startup.aspx HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "localhost"
2016/04/14 00:01:02 [error] 720#0: *15 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /Startup.aspx HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "localhost"
2016/04/14 00:01:02 [crit] 720#0: *15 connect() to unix:/var/run/onlyoffice/onlyoffice3.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /Startup.aspx HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice3.socket:", host: "localhost"
```

I run container with:
```Shell
docker run -i -t -d \
     --name onlyoffice-document-server \
     onlyoffice/documentserver
 docker run -i -t -d \
     --name onlyoffice-community-server \
     --restart=always \
     -p 8080:80 \
     --link onlyoffice-document-server:document_server \
     -v /opt/onlyoffice/logs:/var/log/onlyoffice \
     -v /opt/onlyoffice/data:/var/www/onlyoffice/Data \
     -v /opt/onlyoffice/mysql:/var/lib/mysql \
     onlyoffice/communityserver
```

I have ran the `ln -s /var/run/onlyoffice/onlyoffice2.socket /var/run/onlyoffice/onlyoffice3.socket` on my `onlyoffice/communityserver` container but the issue persists.

**Comment by C-Duv** [comment]
Can `--userns-remap` and `--userns` Docker options (of `docker daemon` and `docker run`) be of any use here?

**Comment by ibnpetr** [comment]
We do not currently use --userns-remap and --userns options. All commands inside the containers should be performed with sudo.

**Comment by C-Duv** [comment]
OK, I thought it could help with the UID and GID of "mounted" volumes.

**Comment by dboecker** [comment]
Hi @C-Duv 

i've performed `chown -R 104:33 /var/run/onlyoffice/onlyoffice3.socket`, where 104 is the user 'onlyoffice' and 33 is the user 'www-data' in my docker-container, those are the same as the chowned of /var/run/onlyoffice/onlyoffice2.socket. this was my solution for this issue.

**Comment by ibnpetr** [comment]
The fix for onlyoffice3.socket issue will be included into the next release
There will be no need to link it to onlyoffice2.socket or use some workarounds
Thank you all for your patience

**Comment by ashwinrayaprolu1984** [comment]
I tried below stuff.. But still i get same issue
ln -s /var/run/onlyoffice/onlyoffice2.socket /var/run/onlyoffice/onlyoffice3.socket
chown -R 104:33 /var/run/onlyoffice/onlyoffice3.socket

![image](https://cloud.githubusercontent.com/assets/8037381/16353424/ddb2c5ae-3a2e-11e6-86e3-e0c71475d9cb.png)

![image](https://cloud.githubusercontent.com/assets/8037381/16353427/ebd4ced4-3a2e-11e6-8df5-e70cd758ea80.png)

I want to evaluate this and this is first time i'm installing with no success
